dashboards:
- name: kubevirt-containerized-data-importer-presubmits
- name: kubevirt-presubmits
- name: kubevirt-periodics
- name: kubevirt-libguestfs-appliance-periodics
- name: kubevirt-hyperconverged-cluster-operator-presubmits
- name: kubevirt-hyperconverged-cluster-operator-periodics

dashboard_groups:
- name: kubevirt
  dashboard_names:
  - kubevirt-containerized-data-importer-presubmits
  - kubevirt-presubmits
  - kubevirt-periodics
  - kubevirt-libguestfs-appliance-periodics
  - kubevirt-hyperconverged-cluster-operator-presubmits
  - kubevirt-hyperconverged-cluster-operator-periodics
